Update deployer to newer version
jalogut/magento2-deployer-plus pull request #72
Opened 2020-12-17 20:01 UTC by tshabatyn

The old version of deployer throws the following error in the Docker container.
```
PHP Fatal error:  require(): Failed opening required 'recipe/common.php' (include_path='phar:///var/www/html/bin/dep/bin/../:.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/jalogut/magento2-deployer-plus/recipe/magento_2_2_5.php on line 13
```

2021-12-29 10:00 UTC, erfanimani commented
LGTM, happy to merge this in. What do you think @sprankhub?

2021-12-29 13:29 UTC, sprankhub requested changes

2021-12-29 13:29 UTC, sprankhub commented on .travis.yml
> +  - php composer-setup.php --version=1.10.19
```suggestion
  - php composer-setup.php --1
```

Why do we fix this to a specific version? I suggest using at least the latest v1 version. Or can we even switch to v2?

2021-12-29 14:08 UTC, erfanimani commented on .travis.yml
> +  - php composer-setup.php --version=1.10.19
I've been using this with Composer 2 just fine, so it probably could do without a version

2022-02-23 09:15 UTC, paulophagula commented on .travis.yml
> +  - php composer-setup.php --version=1.10.19
Indeed, composer 2 is now supported on both 2.3 and 2.4, so I agree that there's no need to hardcore composer version to v1

2022-10-02 06:16 UTC, erfanimani commented
Closing this one as I've created a newer PR which includes this one (https://github.com/jalogut/magento2-deployer-plus/pull/80)

2022-10-02 06:16 UTC, closed without merging